#!/bin/sh

# Set up the monitor daemon to autostart
AUTOSTART_DIR="$SNAP_USER_DATA/.config/autostart"
AUTOSTART_FILE="$SNAP/usr/etc/xdg/autostart/org.gnome.DejaDup.Monitor.desktop"
mkdir -p "$AUTOSTART_DIR"
cp --update "$AUTOSTART_FILE" "$AUTOSTART_DIR"

export PATH="$SNAP/bin:$SNAP/usr/bin:$PATH"

# Without this line we don't seem to properly watch dconf changes.
# The snap default is this dir, plus a "snap.deja-dup" directory.
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

# To make gvfs-backend and its GVFS url parsing work, we need this next line
export LD_LIBRARY_PATH="$SNAP/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET/gvfs:$LD_LIBRARY_PATH"

# Fixes a crash
export GTK_EXE_PREFIX="$SNAP/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET"

# Point at core18's Python interpreter
export PATH="/snap/core18/current/usr/bin:$PATH"

# Point at our internal python packages
export PYTHONPATH="$SNAP/lib/python3.6/site-packages:$PYTHONPATH"

# Prevents a crash when we start yelp
# It's set by desktop helpers, but doesn't seem necessary
unset GDK_PIXBUF_MODULE_FILE

export DEJA_DUP_MONITOR_EXEC="/snap/bin/deja-dup.monitor"
exec "$@"
