#!/bin/sh
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry

# Set up the monitor daemon to autostart
AUTOSTART_DIR="$SNAP_USER_DATA/.config/autostart"
AUTOSTART_FILE="$SNAP/usr/etc/xdg/autostart/org.gnome.DejaDup.Monitor.desktop"
mkdir -p "$AUTOSTART_DIR"
cp --update "$AUTOSTART_FILE" "$AUTOSTART_DIR"

export PATH="$SNAP/bin:$SNAP/usr/bin:$PATH"

# Once our desktop filename can match our application ID, we can probably drop
# the following fixes for notifications.
# https://forum.snapcraft.io/t/proposal-allow-snaps-to-specify-their-exact-desktop-file-id/12689/2
export GNOTIFICATION_BACKEND=freedesktop
export DEJA_DUP_NOTIFICATION_ICON="$SNAP/usr/share/icons/hicolor/symbolic/apps/org.gnome.DejaDup-symbolic.svg"
# Disable prompt under fdo notify backend, since it can't autostart us when
# we aren't already open, and that's usually the case with the prompt
gsettings set org.gnome.DejaDup prompt-check disabled

# Without this line we don't seem to properly watch dconf changes.
# The snap default is this dir, plus a "snap.deja-dup" directory.
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

# To make gvfs-backend and its GVFS url parsing work, we need this next line
export LD_LIBRARY_PATH="$SNAP/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET/gvfs:$LD_LIBRARY_PATH"

# Fixes a crash
export GTK_EXE_PREFIX="$SNAP/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET"

# Point at our internal python packages
export PYTHONHOME="$SNAP/usr"
export PYTHONPATH="$SNAP/lib/python3.8/site-packages"

export DEJA_DUP_MONITOR_EXEC="/snap/bin/deja-dup.monitor"
exec "$@"
