# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry
---
name: deja-dup
license: GPL-3.0+

# Disabled for now - store caught our builds in manual review because of the
# unexpected 'links' attribute in the resulting snap.yml
#website: https://wiki.gnome.org/Apps/DejaDup
#source-code: https://gitlab.gnome.org/World/deja-dup.git
#issues: https://gitlab.gnome.org/World/deja-dup/-/issues
#donation: https://wiki.gnome.org/Apps/DejaDup/Donate
#contact: https://discourse.gnome.org/tags/c/applications/7/deja-dup

grade: stable
confinement: classic
base: core20
adopt-info: deja-dup
assumes: [command-chain]

apps:
  deja-dup:
    adapter: full
    command-chain: [bin/desktop-launch, wrapper]
    command: usr/bin/deja-dup
    common-id: org.gnome.DejaDup

  monitor:
    adapter: full
    command-chain: [bin/desktop-launch, wrapper]
    command: usr/libexec/deja-dup/deja-dup-monitor
    autostart: org.gnome.DejaDup.Monitor.desktop

parts:
  dump:
    plugin: dump
    source: ./local

  duplicity:
    plugin: python
    # Make sure we have pip 21 or higher, to fix cryptography module build.
    # (It needs compiled rust code.) Can remove next time we bump our base.
    override-pull: |
      pip install -vvv -U pip
      pip --version
      snapcraftctl pull
    override-build: |
      pip --version
      snapcraftctl build
    constraints:
      - ${SNAPCRAFT_PROJECT_DIR}/constraints.txt
    python-packages:
      - duplicity
      - pydrive2
      - pygobject
    build-packages:
      - libgirepository1.0-dev
      - librsync-dev
      - libssl-dev
    stage-packages:
      - gpg
      - libgirepository-1.0-1
      - librsync2
    prime:
      - -bin/python
      - -bin/python3

  libhandy:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/libhandy.git
    source-type: git
    source-tag: 1.0.3
    meson-parameters:
      - -Dexamples=false
      - -Dtests=false

  deja-dup:
    after: [libhandy]
    plugin: meson
    source: https://gitlab.gnome.org/World/deja-dup.git
    source-type: git
    source-branch: '42'
    meson-parameters:
      - --buildtype=release
      - --prefix=/snap/deja-dup/current/usr
    parse-info: [usr/share/metainfo/org.gnome.DejaDup.appdata.xml]
    organize:
      snap/deja-dup/current: .
    build-environment:
      # To find libhandy-1.vapi
      - XDG_DATA_DIRS: "/usr/share:$SNAPCRAFT_STAGE/usr/local/share"
    build-packages:
      - gettext
      - itstool
      - libglib2.0-bin
      - libglib2.0-dev
      - libgpg-error-dev
      - libgtk-3-dev
      - libjson-glib-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - valac
    stage-packages:
      - gvfs-backends
      - libgtk-3-0
      - libjson-glib-1.0-0
      - libsecret-1-0
      - libsoup2.4-1
    override-pull: |
      snapcraftctl pull
      patch -p1 -N < ${SNAPCRAFT_PROJECT_DIR}/no-help.diff
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.gnome.DejaDup.svg|' usr/share/applications/org.gnome.DejaDup.desktop

  # Done separately because the other parts freaks out if we try to stage python
  python:
    plugin: nil
    after: [duplicity, deja-dup]
    stage-packages:
      - python3-minimal
      - python3.8-minimal


  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
      - FLAVOR=gtk3
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
