# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry
---
name: deja-dup
license: GPL-3.0+

website: https://wiki.gnome.org/Apps/DejaDup
source-code: https://github.com/deja-dup/snap.git
issues: https://gitlab.gnome.org/World/deja-dup/-/issues
donation: https://liberapay.com/DejaDup
contact:
  - https://discourse.gnome.org/tags/c/applications/7/deja-dup
  - https://matrix.to/#/#deja-dup:gnome.org

grade: stable
confinement: classic
base: core22
compression: lzo
adopt-info: deja-dup
assumes: [command-chain]

# - Could point python at core22 instead of bundling it in.
# - Could bundle gnome into ourselves and chop it up

# Hooks:
# hooks-configure-desktop comes from fonts

apps:
  deja-dup:
    command-chain: [wrapper]
    command: usr/bin/deja-dup
    common-id: org.gnome.DejaDup

  monitor:
    command-chain: [wrapper]
    command: usr/libexec/deja-dup/deja-dup-monitor
    autostart: org.gnome.DejaDup.Monitor.desktop

parts:
  dump:
    plugin: dump
    source: ./local

  duplicity:
    plugin: python
    source: https://gitlab.com/duplicity/duplicity.git
    source-type: git
    source-tag: rel.0.8.23
    override-pull: |
      craftctl default
      sed -i 's/$version/0.8.23/g' bin/* duplicity/__init__.py
    python-packages:
      - pydrive2
      - pygobject
      - requests-oauthlib
    build-packages:
      - cargo # to build cryptography
      - libcairo2-dev # to build pycairo
      - libgirepository1.0-dev
      - librsync-dev
      - libssl-dev
      - rustc # to build cryptography
    stage-packages:
      - gpg
      - libgirepository-1.0-1
      - librsync2
    stage:
      - bin/duplicity
      - lib
      - usr/bin/gpg
      - usr/lib

  deja-dup:
    after: [duplicity]
    plugin: meson
    source: https://gitlab.gnome.org/World/deja-dup.git
    source-type: git
    source-tag: '43.4'
    meson-parameters:
      - --buildtype=release
      - --prefix=/snap/deja-dup/current/usr
      - -Denable_restic=true
    parse-info: [usr/share/metainfo/org.gnome.DejaDup.metainfo.xml]
    organize:
      snap/deja-dup/current: .
    build-environment:
      - LD_LIBRARY_PATH: /snap/core22/current/usr/lib/$CRAFT_ARCH_TRIPLET
    build-packages:
      - appstream # for ITS rules for metainfo
      - gettext
      - itstool
      - libadwaita-1-dev
      - libgpg-error-dev
      - libjson-glib-dev
      - libsecret-1-dev
      - libsoup-3.0-dev
      - meson
      - ninja-build
      - valac
    stage-packages:
      - gvfs-backends
      - libadwaita-1-0
      - libjson-glib-1.0-0
      - librsvg2-common # pixbuf loaders
      - libsecret-1-0
      - libsoup-3.0-0
      - util-linux # ionice and chrt
    override-prime: |
      craftctl default
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.gnome.DejaDup.svg|' usr/share/applications/org.gnome.DejaDup.desktop

  rclone:
    plugin: go
    source: https://github.com/rclone/rclone.git
    source-type: git
    source-tag: v1.58.1
    build-snaps:
      - go

  restic:
    plugin: go
    source: https://github.com/restic/restic.git
    source-type: git
    source-tag: v0.13.1
    build-snaps:
      - go

  # Done separately because the other parts freaks out if we try to stage python
  python:
    plugin: nil
    after: [duplicity, deja-dup]
    stage-packages:
      - libpython3.10-minimal
      - libpython3.10-stdlib
      - python3-minimal
      - python3.10-minimal

  finalize:
    plugin: nil
    after: [python]
    build-packages:
      - patchelf
    override-prime: |
      craftctl default
      # snapcraft will set RPATH for us. But it may get some things wrong.
      # (A) its order seems undefined
      # (B) for deja-dup-monitor at least, it only adds an core path, not knowing
      #     that actually, we'd prefer our own glib
      # So what we want to do is to set specific rpaths for all libraries and
      # executables.
      export BARE_INTERPRETER=`patchelf --print-interpreter /snap/core22/current/bin/ls`
      export SET_INTERP="patchelf --set-interpreter /snap/core22/current$BARE_INTERPRETER"
      export SET_RPATH="patchelf --force-rpath --set-rpath /snap/deja-dup/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/deja-dup/current/usr/lib/$CRAFT_ARCH_TRIPLET/deja-dup:/snap/deja-dup/current/usr/lib/$CRAFT_ARCH_TRIPLET/gvfs:/snap/core22/current/usr/lib/$CRAFT_ARCH_TRIPLET"
      find lib usr -name '*.so*' -exec $SET_RPATH {} \;
      find lib usr -name '*.so*' -exec $SET_INTERP {} \;
      find bin usr/bin usr/libexec -exec $SET_RPATH {} \;
      find bin usr/bin usr/libexec -exec $SET_INTERP {} \;
      # Fix shebangs to not reference /usr/bin/env
      grep -rl '#!/usr/bin/env python3' | xargs sed -i 's|#!/usr/bin/env python3|#!/snap/deja-dup/current/usr/bin/python3 -s|' || true
      # Compile pixbuf loaders cache
      export GDK_PIXBUF_MODULEDIR=`pwd`/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders
      export GDK_PIXBUF_MODULE_FILE=${GDK_PIXBUF_MODULEDIR}.cache
      env LD_LIBRARY_PATH=`pwd`/usr/lib/$CRAFT_ARCH_TRIPLET usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache
      sed -i "s|`pwd`|/snap/deja-dup/current|g" $GDK_PIXBUF_MODULE_FILE
      # Compile giomodules cache
      gio-querymodules usr/lib/$CRAFT_ARCH_TRIPLET/gio/modules
      # Compile our gschema, but make sure we remove all schemas that aren't ours first
      # (we are using host gsettings, so we want to look at host schemas, not the ones from the build)
      find usr/share/glib-2.0/schemas -mindepth 1 '!' '(' -name org.gnome.DejaDup.gschema.xml -o -name 'org.gtk.gtk4.*.gschema.xml' ')' -delete
      glib-compile-schemas usr/share/glib-2.0/schemas
