# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
---
name: deja-dup
title: Déjà Dup Backup Tool
summary: Keep your important documents safe from disaster
description: |
  Déjà Dup is a simple backup tool. It hides the complexity of backing up the
  Right Way (encrypted, off-site, and regular) and uses duplicity as the
  backend.

  * Support for local, remote, or cloud backup locations such as Google Drive
  * Securely encrypts and compresses your data
  * Incrementally backs up, letting you restore from any particular backup
  * Schedules regular backups
  * Integrates well into your GNOME desktop
icon: org.gnome.DejaDup.svg
license: GPL-3.0+

grade: stable
confinement: classic
base: core18
adopt-info: deja-dup
assumes: [command-chain]

apps:
  deja-dup:
    adapter: full
    command-chain: [bin/desktop-launch, wrapper]
    command: usr/bin/deja-dup
    desktop: usr/share/applications/org.gnome.DejaDup.desktop
    common-id: org.gnome.DejaDup

  monitor:
    adapter: full
    command-chain: [bin/desktop-launch, wrapper]
    command: usr/libexec/deja-dup/deja-dup-monitor
    autostart: org.gnome.DejaDup.Monitor.desktop

parts:
  dump:
    plugin: dump
    source: ./local

  duplicity:
    plugin: python
    python-version: python3
    source: https://launchpad.net/duplicity/0.8-series/0.8.06/+download/duplicity-0.8.06.tar.gz
    source-type: tar
    python-packages:
      - boto
      - pydrive  # not packaged in Ubuntu
      - pygobject
      - pyrax  # not packaged in Ubuntu
      - python-swiftclient
      # Deps needed to build
      - pycairo
      - setuptools
      - wheel
    build-packages:
      - libffi-dev  # for cffi from pyrax
      - libgirepository1.0-dev
      - librsync-dev
      - libssl-dev  # for cffi from pyrax
    stage-packages:
      - gpg
      - libgirepository-1.0-1
      - librsync1
    override-prime: |
      snapcraftctl prime
      sed -i 's|!/usr/bin/env python$|!/usr/bin/env python3|' bin/duplicity
      sed -i "s|self.id_cache\[remote_filename\] = drive_file\[u'id'\]|self.id_cache[util.fsdecode(remote_filename)] = drive_file[u'id']|" lib/python3.6/site-packages/duplicity/backends/pydrivebackend.py

  deja-dup:
    plugin: meson
    source: https://gitlab.gnome.org/World/deja-dup
    source-type: git
    source-branch: stable
    meson-parameters:
      - --buildtype=release
      - --prefix=/snap/deja-dup/current/usr
    organize:
      snap/deja-dup/current: .
    build-packages:
      - appstream-util
      - dbus
      - desktop-file-utils
      - gettext
      - itstool
      - libglib2.0-bin
      - libglib2.0-dev
      - libgoa-1.0-dev
      - libgpg-error-dev
      - libgtk-3-dev
      - libjson-glib-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - valac
    stage-packages:
      - gvfs-backends
      - libgoa-1.0-0b
      - libgtk-3-0
      - libjson-glib-1.0-0
      - libsecret-1-0
      - libsoup2.4-1
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(grep version: meson.build -m1 | cut -d\' -f2)"
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=/usr/share/icons/hicolor/scalable/apps/org.gnome.DejaDup.svg|' usr/share/applications/org.gnome.DejaDup.desktop


  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
      - FLAVOR=gtk3
    build-packages:
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
