# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry
---
name: deja-dup
license: GPL-3.0+

# Disabled for now - store caught our builds in manual review because of the
# unexpected 'links' attribute in the resulting snap.yml
#website: https://wiki.gnome.org/Apps/DejaDup
#source-code:
#  - https://gitlab.gnome.org/World/deja-dup.git
#  - https://github.com/deja-dup/snap.git
#issues: https://gitlab.gnome.org/World/deja-dup/-/issues
#donation: https://liberapay.com/DejaDup
#contact:
#  - https://discourse.gnome.org/tags/c/applications/7/deja-dup
#  - https://matrix.to/#/#deja-dup:gnome.org

grade: stable
confinement: classic
base: core20
adopt-info: deja-dup
assumes: [command-chain]

# - Could point python at core20 instead of bundling it in.
# - Could bundle gnome into ourselves and chop it up

# Hooks:
# hooks-configure-desktop comes from fonts

apps:
  deja-dup:
    adapter: full
    command-chain: [wrapper]
    command: usr/bin/deja-dup
    common-id: org.gnome.DejaDup

  monitor:
    adapter: full
    command-chain: [wrapper]
    command: usr/libexec/deja-dup/deja-dup-monitor
    autostart: org.gnome.DejaDup.Monitor.desktop

parts:
  dump:
    plugin: dump
    source: ./local

  duplicity:
    plugin: python
    constraints:
      - ${SNAPCRAFT_PROJECT_DIR}/constraints.txt
    python-packages:
      - duplicity
      - pydrive2
      - pygobject
    build-packages:
      - cargo # to build cryptography
      - libcairo2-dev # to build pycairo
      - libgirepository1.0-dev
      - librsync-dev
      - libssl-dev
      - rustc # to build cryptography
    stage-packages:
      - gpg
      - libgirepository-1.0-1
      - librsync2
    stage:
      - bin/duplicity
      - lib

  gtk:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/gtk.git
    source-type: git
    source-tag: 3.24.30
    meson-parameters:
      - -Ddemos=false
      - -Dexamples=false
      - -Dtests=false
      - --wrap-mode=nodownload
    build-packages:
      - libatk1.0-dev
      - libatk-bridge2.0-dev
      - libepoxy-dev
      - libgdk-pixbuf2.0-dev
      - libpango1.0-dev
      - libwayland-dev
      - libxi-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - wayland-protocols
    stage-packages:
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libepoxy0
      - libffi7
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgraphite2-3
      - libharfbuzz0b
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libxcb-render0
      - libxcb-shm0
      - libxfixes3
      - libxi6
      - libxkbcommon0
      - libxrandr2

  libhandy:
    after: [gtk]
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/libhandy.git
    source-type: git
    source-tag: 1.5.0
    meson-parameters:
      - -Dexamples=false
      - -Dtests=false
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/local/lib:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      # To find gir files
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/local/share:/usr/share

  deja-dup:
    after: [duplicity, gtk, libhandy]
    plugin: meson
    source: https://gitlab.gnome.org/World/deja-dup.git
    source-type: git
    source-branch: '42'
    meson-parameters:
      - --buildtype=release
      - --prefix=/snap/deja-dup/current/usr
    parse-info: [usr/share/metainfo/org.gnome.DejaDup.appdata.xml]
    organize:
      snap/deja-dup/current: .
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/local/lib:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      # To find libhandy-1.vapi
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/local/share:/usr/share
    build-packages:
      - appstream # for ITS rules for metainfo
      - gettext
      - itstool
      - libgpg-error-dev
      - libjson-glib-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - valac
    stage-packages:
      - gvfs-backends
      - libjson-glib-1.0-0
      - librsvg2-common # pixbuf loaders
      - libsecret-1-0
      - libsoup2.4-1
      - util-linux # ionice and chrt
    override-pull: |
      snapcraftctl pull
      patch -p1 -N < ${SNAPCRAFT_PROJECT_DIR}/no-help.diff
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.gnome.DejaDup.svg|' usr/share/applications/org.gnome.DejaDup.desktop

  # Done separately because the other parts freaks out if we try to stage python
  python:
    plugin: nil
    after: [duplicity, deja-dup]
    stage-packages:
      - libpython3.8-minimal
      - libpython3.8-stdlib
      - python3-minimal
      - python3.8-minimal

  finalize:
    plugin: nil
    after: [python]
    build-packages:
      - patchelf
    override-prime: |
      snapcraftctl prime
      # snapcraft will set RPATH for us. But it may get some things wrong.
      # (A) its order seems undefined
      # (B) for deja-dup-monitor at least, it only adds an core path, not knowing
      #     that actually, we'd prefer our own glib
      # So what we want to do is to set specific rpaths for all libraries and
      # executables.
      export PATCHELF="patchelf --force-rpath --set-rpath /snap/deja-dup/current/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/deja-dup/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/deja-dup/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/deja-dup:/snap/deja-dup/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gvfs:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      find usr -name '*.so*' -exec $PATCHELF {} \;
      find usr/bin usr/libexec -exec $PATCHELF {} \;
      # Remove libraries from archive that we have built updated copies of
      cd usr/lib/$SNAPCRAFT_ARCH_TRIPLET; ls ../../local/lib/$SNAPCRAFT_ARCH_TRIPLET -p | grep -v / | xargs rm -f; cd -
      # Fix shebangs to not reference /usr/bin/env
      grep -rl '#!/usr/bin/env python3' | xargs sed -i 's|#!/usr/bin/env python3|#!/snap/deja-dup/current/usr/bin/python3|' || true
      # Compile giomodules cache
      gio-querymodules usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules
      glib-compile-schemas usr/share/glib-2.0/schemas
