# -*- Mode: YAML; indent-tabs-mode: nil; tab-width: 2 -*-
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: Michael Terry
---
name: deja-dup
license: GPL-3.0+

website: https://wiki.gnome.org/Apps/DejaDup
source-code: https://github.com/deja-dup/snap.git
issues: https://gitlab.gnome.org/World/deja-dup/-/issues
donation: https://liberapay.com/DejaDup
contact: https://discourse.gnome.org/tags/c/applications/7/deja-dup

grade: stable
confinement: classic
base: core20
compression: lzo
adopt-info: deja-dup
assumes: [command-chain]

# - Could point python at core20 instead of bundling it in.
# - Could bundle gnome into ourselves and chop it up

# Hooks:
# hooks-configure-desktop comes from fonts

apps:
  deja-dup:
    command-chain: [wrapper]
    command: usr/bin/deja-dup
    common-id: org.gnome.DejaDup

  monitor:
    command-chain: [wrapper]
    command: usr/libexec/deja-dup/deja-dup-monitor
    autostart: org.gnome.DejaDup.Monitor.desktop

parts:
  dump:
    plugin: dump
    source: ./local

  duplicity:
    plugin: python
    source: https://gitlab.com/duplicity/duplicity.git
    source-depth: 1
    source-type: git
    source-tag: rel.2.1.4
    override-pull: |
      snapcraftctl pull
      patch -p1 < ${SNAPCRAFT_PROJECT_DIR}/mount.patch
      sed -i 's/$version/2.1.4/g' bin/* duplicity/__init__.py
    python-packages:
      - pydrive2
      - pygobject
      - requests-oauthlib
    build-packages:
      - cargo # to build cryptography
      - libcairo2-dev # to build pycairo
      - libgirepository1.0-dev
      - librsync-dev
      - libssl-dev
      - rustc # to build cryptography
    stage-packages:
      - gpg
      - libgirepository-1.0-1
      - librsync2
    stage:
      - bin/duplicity
      - lib
      - usr/bin/gpg
      - usr/lib

  glib:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/glib.git
    source-depth: 1
    source-type: git
    source-tag: 2.78.0
    meson-parameters:
      - -Dtests=false
      - --wrap-mode=nodownload

  harfbuzz:
    after: [glib]
    plugin: meson
    source: https://github.com/harfbuzz/harfbuzz.git
    source-depth: 1
    source-type: git
    source-tag: 8.2.1
    meson-parameters:
      - -Dtests=disabled
      - --wrap-mode=nodownload

  pango:
    after: [glib, harfbuzz]
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/pango.git
    source-depth: 1
    source-type: git
    source-tag: 1.50.12
    meson-parameters:
      - --wrap-mode=nodownload
    build-environment:
      # To find gir files
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/local/share:/usr/share
    build-packages:
      - libfribidi-dev
      - libgirepository1.0-dev
    stage-packages:
      - libfribidi0

  wayland:
    plugin: meson
    source: https://gitlab.freedesktop.org/wayland/wayland.git
    source-depth: 1
    source-type: git
    source-tag: '1.22.0'
    meson-parameters:
      - -Ddocumentation=false
      - -Ddtd_validation=false
      - -Dtests=false
      - --wrap-mode=nodownload

  wayland-protocols:
    plugin: meson
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-depth: 1
    source-type: git
    source-tag: '1.32'
    meson-parameters:
      - -Dtests=false
      - --wrap-mode=nodownload

  gtk:
    after: [glib, harfbuzz, pango, wayland, wayland-protocols]
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/gtk.git
    source-depth: 1
    source-type: git
    source-tag: 4.12.2
    meson-parameters:
      - -Dbuild-demos=false
      - -Dbuild-examples=false
      - -Dbuild-tests=false
      - -Dbuild-testsuite=false
      - -Dintrospection=enabled
      - -Dmedia-gstreamer=disabled
      - --wrap-mode=nodownload
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/local/lib:$SNAPCRAFT_STAGE/usr/local/lib/vala-0.56:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      # To find gir files
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/local/share:/usr/share
      # To find wayland-scanner
      - PATH: "$SNAPCRAFT_STAGE/usr/local/bin:$PATH"
    build-packages:
      - libepoxy-dev
      - libgdk-pixbuf2.0-dev
      - libgirepository1.0-dev
      - libgraphene-1.0-dev
      - libtiff-dev
      - libxcursor-dev
      - libxdamage-dev
      - libxi-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - sassc
    stage-packages:
      - libcairo-gobject2
      - libcairo-script-interpreter2
      - libcairo2
      - libdatrie1
      - libepoxy0
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libgraphene-1.0-0
      - libgraphite2-3
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1

  vala:
    after: [gtk]
    plugin: autotools
    source: https://gitlab.gnome.org/GNOME/vala.git
    source-depth: 1
    source-type: git
    source-tag: 0.56.13
    build-packages:
      - autoconf-archive
      - bison
      - flex
      - libgraphviz-dev
    prime: [-**]

  libappstream:
    after: [glib]
    plugin: meson
    source: https://github.com/ximion/appstream.git
    source-depth: 1
    source-type: git
    source-tag: v0.14.6
    meson-parameters:
      - -Dapidocs=false
      - -Dstemming=false
      - --wrap-mode=nodownload
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/local/lib:$SNAPCRAFT_STAGE/usr/local/lib/vala-0.56:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    build-packages:
      - docbook-xsl
      - gperf
      - libcurl4-gnutls-dev
      - liblmdb-dev
      - libyaml-dev
      - xsltproc
    stage-packages:
      - libcurl3-gnutls
      - liblmdb0
      - libyaml-0-2

  libadwaita:
    after: [gtk, libappstream, vala]
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/libadwaita.git
    source-depth: 1
    source-type: git
    source-tag: 1.4.0
    meson-parameters:
      - -Dexamples=false
      - -Dtests=false
      - --wrap-mode=nodownload
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/local/lib:$SNAPCRAFT_STAGE/usr/local/lib/vala-0.56:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      # To find gir files
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/local/share:/usr/share
      # To find vapigen
      - PATH: "$SNAPCRAFT_STAGE/usr/local/bin:$PATH"

  deja-dup:
    after: [duplicity, gtk, libadwaita]
    plugin: meson
    source: https://gitlab.gnome.org/World/deja-dup.git
    source-depth: 1
    source-type: git
    source-commit: 585b723da27fdc6ad5c2a3b27858fdc9056f0038
    meson-parameters:
      - --buildtype=release
      - --prefix=/snap/deja-dup/current/usr
      - -Denable_restic=true
    parse-info: [usr/share/metainfo/org.gnome.DejaDup.metainfo.xml]
    organize:
      snap/deja-dup/current: .
    build-environment:
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_STAGE/usr/local/lib:$SNAPCRAFT_STAGE/usr/local/lib/vala-0.56:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      # To find libadwaita-1.vapi
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/local/share:/usr/share
      # To find gtk4-update-icon-cache
      - PATH: "$SNAPCRAFT_STAGE/usr/local/bin:$PATH"
    build-packages:
      - gettext
      - itstool
      - libgpg-error-dev
      - libjson-glib-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - valac
    stage-packages:
      - gvfs-backends
      - libjson-glib-1.0-0
      - librsvg2-common # pixbuf loaders
      - libsecret-1-0
      - libsoup2.4-1
      - util-linux # ionice and chrt
    override-pull: |
      snapcraftctl pull
      patch -p1 -N -R < ${SNAPCRAFT_PROJECT_DIR}/soup3.patch
    override-prime: |
      snapcraftctl prime
      sed -i 's|Icon=.*|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/org.gnome.DejaDup.svg|' usr/share/applications/org.gnome.DejaDup.desktop

  rclone:
    plugin: go
    source: https://github.com/rclone/rclone.git
    source-depth: 1
    source-type: git
    source-tag: v1.62.2

  restic:
    plugin: go
    source: https://github.com/restic/restic.git
    source-depth: 1
    source-type: git
    source-tag: v0.15.2

  # Done separately because the other parts freaks out if we try to stage python
  python:
    plugin: nil
    after: [duplicity, deja-dup]
    stage-packages:
      - libpython3.8-minimal
      - libpython3.8-stdlib
      - python3-minimal
      - python3.8-minimal

  finalize:
    plugin: nil
    after: [python]
    build-packages:
      - patchelf
    override-prime: |
      snapcraftctl prime
      # snapcraft will set RPATH for us. But it may get some things wrong.
      # (A) its order seems undefined
      # (B) for deja-dup-monitor at least, it only adds an core path, not knowing
      #     that actually, we'd prefer our own glib
      # So what we want to do is to set specific rpaths for all libraries and
      # executables.
      export PATCHELF="patchelf --force-rpath --set-rpath /snap/deja-dup/current/usr/local/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/deja-dup/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/deja-dup/current/lib/$SNAPCRAFT_ARCH_TRIPLET:/snap/deja-dup/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/deja-dup:/snap/deja-dup/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gvfs:/snap/core20/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
      find lib usr -name '*.so*' -exec $PATCHELF {} \;
      find bin usr/bin usr/libexec -exec $PATCHELF {} \;
      # Remove libraries from archive that we have built updated copies of
      cd usr/lib/$SNAPCRAFT_ARCH_TRIPLET; ls ../../local/lib/$SNAPCRAFT_ARCH_TRIPLET -p | grep -v / | xargs rm -f; cd -
      # Fix shebangs to not reference /usr/bin/env
      grep -rl '#!/usr/bin/env python3' | xargs sed -i 's|#!/usr/bin/env python3|#!/snap/deja-dup/current/usr/bin/python3 -s|' || true
      # Compile pixbuf loaders cache
      export GDK_PIXBUF_MODULEDIR=`pwd`/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders
      export GDK_PIXBUF_MODULE_FILE=${GDK_PIXBUF_MODULEDIR}.cache
      usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache
      sed -i "s|`pwd`|/snap/deja-dup/current|g" $GDK_PIXBUF_MODULE_FILE
      # Compile giomodules cache
      gio-querymodules usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gio/modules
      # Compile our gschema, but make sure we remove all schemas that aren't ours first
      # (we are using host gsettings, so we want to look at host schemas, not the ones from the build)
      find usr/share/glib-2.0/schemas -mindepth 1 ! -name org.gnome.DejaDup.gschema.xml -delete
      cp usr/local/share/glib-2.0/schemas/*.xml usr/share/glib-2.0/schemas
      glib-compile-schemas usr/share/glib-2.0/schemas
